### ISSUE TITLE
Instructions needed

### ISSUE THREAD

**Issue by zllovesuki** [zerocowl/oauth-moleculer#2]
Please provide a minimal example of integration with moleculer... OAuth is confusing enough already.

**Comment by AndreMaz** [comment]
Agree 

@zerocowl can you improve the docs?

**Comment by zerocowl** [comment]
@AndreMaz Yes, I'll do it this week.

**Comment by AndreMaz** [comment]
Thnks 👍

**Comment by AndreMaz** [comment]
@zerocowl any update on this?

**Comment by davidroman0O** [comment]
@zerocowl Your week is pretty long 😄  ahah

**Comment by zerocowl** [comment]
Sorry :pensive:, it was a very chaotic _week_  :disappointed:  :disappointed: :sweat_smile:
I'm updating some codes, dependencies and documenting everything better, I'm also finishing translating some things at the moment and until the middle of the week I publish everything :dart:

**Comment by xgenvn** [comment]
@zerocowl  
The current implementation looks like a provider for oauth-server if I'm correct.
There is also an active project working on a general provider, maybe we can use and build a thin layer upon instead of build from start. 
Just for reference: https://github.com/panva/node-oidc-provider

**Comment by zerocowl** [comment]
@xgenvn
 Yes, it's basically a provider.
Great idea, I will study this reference project. Could you open an issue just about it?
